name: Create and publish image

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-solvers-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Check solvers image
        id: check_modification
        # grep command return code is 0 if match found
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'solvers/'; then
            echo "folder_modified=true >> $GITHUB_OUTPUT"
          else
            echo "folder_modified=false >> $GITHUB_OUTPUT"
          fi

      - name: Build and push
        if: steps.check_modification.outputs.folder_modified == 'true'
        uses: docker/build-push-action@v5
        with:
          context: solvers
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Cache solvers image
        run: |
          echo "gonna cache if didnt"


  build-and-run-problem:
    needs: build-and-push-solvers-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CACHE_PATH: ci/cache/docker/solvers
      CACHE_IMAGE_NAME: ci/cache/docker/solvers/solvers.tar
      LATEST_IMAGE_PATH: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache solvers image
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATH }}
          key: solvers

      - name: Create cache directory
        if: steps.cache.outputs.cache-hit != 'true'
        run: mkdir -p ${{ env.CACHE_PATH }}

      - name: Add base image to cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker pull ${{ env.LATEST_IMAGE_PATH }  && docker image save ${{ env.LATEST_IMAGE_PATH }} --output ${{ env.CACHE_IMAGE_NAME }}

      - name: Load base image from cache
        if: steps.cache-docker-miniconda.outputs.cache-hit == 'true'
        run: docker image load --input ${{ env.CACHE_IMAGE_NAME }}

      - name: Build and test
        run: | 
          docker build -t test .
          docker run --rm test
