name: Create and publish image

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-solvers-image:
    runs-on: ubuntu-latest
    outputs:
      has_run: ${{ steps.check.outputs.run }}
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'solvers') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: solvers
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  build-and-run-problem:
    needs: build-and-push-solvers-image
    if: needs.optional_job.outputs.has_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: donker pull the good stuff
        run: docker pull ghcr.io/mihsamusev/docker_lp_solvers:latest
